FROM golang:onbuild
#FROM golang:1.13.7-alpine3.11
#FROM golang:latest
#RUN mkdir /app
#ADD . /app/
#WORKDIR /app

#RUN go get -d -v ./...
#RUN go install -v ./...

#RUN go build -o main .
#CMD ["/app/main"]

EXPOSE 8100

#docker build -t jpedro1992/sfc-controller:0.0.2 .